#Bot Config
token:
appid:
version: 1.2.0

#Databse Config
host:
user:
password:
database: Irminsul

#Bot Settings
createChannelWithPrefix: false
autoDeleteEmptyVoiceChannel: true
enabledVCAdministratorGuilds:
  - 100000000 # your guild id here